// Code generated by protoc-gen-go. DO NOT EDIT.
// source: servers/hello/hello.proto

package grpc_service

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The request message containing the user's name.
type PostHelloRequest struct {
	Greeting             string   `protobuf:"bytes,1,opt,name=greeting,proto3" json:"greeting,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostHelloRequest) Reset()         { *m = PostHelloRequest{} }
func (m *PostHelloRequest) String() string { return proto.CompactTextString(m) }
func (*PostHelloRequest) ProtoMessage()    {}
func (*PostHelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6b55328bf9a1bcc, []int{0}
}

func (m *PostHelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostHelloRequest.Unmarshal(m, b)
}
func (m *PostHelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostHelloRequest.Marshal(b, m, deterministic)
}
func (m *PostHelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostHelloRequest.Merge(m, src)
}
func (m *PostHelloRequest) XXX_Size() int {
	return xxx_messageInfo_PostHelloRequest.Size(m)
}
func (m *PostHelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PostHelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PostHelloRequest proto.InternalMessageInfo

func (m *PostHelloRequest) GetGreeting() string {
	if m != nil {
		return m.Greeting
	}
	return ""
}

// The response message containing the greetings
type PostHelloReply struct {
	Greeting             string   `protobuf:"bytes,1,opt,name=greeting,proto3" json:"greeting,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostHelloReply) Reset()         { *m = PostHelloReply{} }
func (m *PostHelloReply) String() string { return proto.CompactTextString(m) }
func (*PostHelloReply) ProtoMessage()    {}
func (*PostHelloReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6b55328bf9a1bcc, []int{1}
}

func (m *PostHelloReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostHelloReply.Unmarshal(m, b)
}
func (m *PostHelloReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostHelloReply.Marshal(b, m, deterministic)
}
func (m *PostHelloReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostHelloReply.Merge(m, src)
}
func (m *PostHelloReply) XXX_Size() int {
	return xxx_messageInfo_PostHelloReply.Size(m)
}
func (m *PostHelloReply) XXX_DiscardUnknown() {
	xxx_messageInfo_PostHelloReply.DiscardUnknown(m)
}

var xxx_messageInfo_PostHelloReply proto.InternalMessageInfo

func (m *PostHelloReply) GetGreeting() string {
	if m != nil {
		return m.Greeting
	}
	return ""
}

// The request message containing the user's name.
type GetHelloRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetHelloRequest) Reset()         { *m = GetHelloRequest{} }
func (m *GetHelloRequest) String() string { return proto.CompactTextString(m) }
func (*GetHelloRequest) ProtoMessage()    {}
func (*GetHelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6b55328bf9a1bcc, []int{2}
}

func (m *GetHelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHelloRequest.Unmarshal(m, b)
}
func (m *GetHelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHelloRequest.Marshal(b, m, deterministic)
}
func (m *GetHelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHelloRequest.Merge(m, src)
}
func (m *GetHelloRequest) XXX_Size() int {
	return xxx_messageInfo_GetHelloRequest.Size(m)
}
func (m *GetHelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetHelloRequest proto.InternalMessageInfo

// The response message containing the greetings
type GetHelloReply struct {
	Greetings            []string `protobuf:"bytes,1,rep,name=greetings,proto3" json:"greetings,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetHelloReply) Reset()         { *m = GetHelloReply{} }
func (m *GetHelloReply) String() string { return proto.CompactTextString(m) }
func (*GetHelloReply) ProtoMessage()    {}
func (*GetHelloReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6b55328bf9a1bcc, []int{3}
}

func (m *GetHelloReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHelloReply.Unmarshal(m, b)
}
func (m *GetHelloReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHelloReply.Marshal(b, m, deterministic)
}
func (m *GetHelloReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHelloReply.Merge(m, src)
}
func (m *GetHelloReply) XXX_Size() int {
	return xxx_messageInfo_GetHelloReply.Size(m)
}
func (m *GetHelloReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHelloReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetHelloReply proto.InternalMessageInfo

func (m *GetHelloReply) GetGreetings() []string {
	if m != nil {
		return m.Greetings
	}
	return nil
}

func init() {
	proto.RegisterType((*PostHelloRequest)(nil), "hello.PostHelloRequest")
	proto.RegisterType((*PostHelloReply)(nil), "hello.PostHelloReply")
	proto.RegisterType((*GetHelloRequest)(nil), "hello.GetHelloRequest")
	proto.RegisterType((*GetHelloReply)(nil), "hello.GetHelloReply")
}

func init() { proto.RegisterFile("servers/hello/hello.proto", fileDescriptor_d6b55328bf9a1bcc) }

var fileDescriptor_d6b55328bf9a1bcc = []byte{
	// 229 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2c, 0x4e, 0x2d, 0x2a,
	0x4b, 0x2d, 0x2a, 0xd6, 0xcf, 0x48, 0xcd, 0xc9, 0xc9, 0x87, 0x90, 0x7a, 0x05, 0x45, 0xf9, 0x25,
	0xf9, 0x42, 0xac, 0x60, 0x8e, 0x92, 0x1e, 0x97, 0x40, 0x40, 0x7e, 0x71, 0x89, 0x07, 0x88, 0x13,
	0x94, 0x5a, 0x58, 0x9a, 0x5a, 0x5c, 0x22, 0x24, 0xc5, 0xc5, 0x91, 0x5e, 0x94, 0x9a, 0x5a, 0x92,
	0x99, 0x97, 0x2e, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x19, 0x04, 0xe7, 0x2b, 0xe9, 0x70, 0xf1, 0x21,
	0xa9, 0x2f, 0xc8, 0xa9, 0xc4, 0xab, 0x5a, 0x90, 0x8b, 0xdf, 0x3d, 0x15, 0xc5, 0x70, 0x25, 0x5d,
	0x2e, 0x5e, 0x84, 0x10, 0x48, 0xbf, 0x0c, 0x17, 0x27, 0x4c, 0x7d, 0xb1, 0x04, 0xa3, 0x02, 0xb3,
	0x06, 0x67, 0x10, 0x42, 0xc0, 0xa8, 0x85, 0x91, 0x8b, 0xdd, 0x1d, 0xc4, 0x4b, 0x2d, 0x12, 0xb2,
	0xe5, 0xe2, 0x84, 0xdb, 0x2d, 0x24, 0xae, 0x07, 0xf1, 0x0d, 0xba, 0xeb, 0xa5, 0x44, 0x31, 0x25,
	0x0a, 0x72, 0x2a, 0x95, 0x18, 0x84, 0xac, 0xb8, 0x38, 0x60, 0x36, 0x0b, 0x89, 0x41, 0x15, 0xa1,
	0xb9, 0x4e, 0x4a, 0x04, 0x43, 0x1c, 0xac, 0xd7, 0xc9, 0x98, 0x4b, 0x2e, 0x33, 0x5f, 0x2f, 0x23,
	0x31, 0x2f, 0x25, 0x27, 0xb5, 0x48, 0x2f, 0xb5, 0x22, 0x31, 0xb7, 0x20, 0x27, 0xb5, 0x18, 0xa2,
	0xb8, 0x3c, 0xbf, 0x28, 0x27, 0xc5, 0x89, 0x1f, 0xac, 0x3e, 0x1c, 0xc4, 0x0e, 0x00, 0x05, 0x70,
	0x00, 0x63, 0x12, 0x1b, 0x38, 0xa4, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0xb3, 0x59, 0xe3,
	0xb3, 0x86, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// GreeterClient is the client API for Greeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GreeterClient interface {
	// Saves a greeting
	PostHello(ctx context.Context, in *PostHelloRequest, opts ...grpc.CallOption) (*PostHelloReply, error)
	// Retrieves a greeting
	GetHello(ctx context.Context, in *GetHelloRequest, opts ...grpc.CallOption) (*GetHelloReply, error)
}

type greeterClient struct {
	cc grpc.ClientConnInterface
}

func NewGreeterClient(cc grpc.ClientConnInterface) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) PostHello(ctx context.Context, in *PostHelloRequest, opts ...grpc.CallOption) (*PostHelloReply, error) {
	out := new(PostHelloReply)
	err := c.cc.Invoke(ctx, "/hello.Greeter/PostHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) GetHello(ctx context.Context, in *GetHelloRequest, opts ...grpc.CallOption) (*GetHelloReply, error) {
	out := new(GetHelloReply)
	err := c.cc.Invoke(ctx, "/hello.Greeter/GetHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GreeterServer is the server API for Greeter service.
type GreeterServer interface {
	// Saves a greeting
	PostHello(context.Context, *PostHelloRequest) (*PostHelloReply, error)
	// Retrieves a greeting
	GetHello(context.Context, *GetHelloRequest) (*GetHelloReply, error)
}

// UnimplementedGreeterServer can be embedded to have forward compatible implementations.
type UnimplementedGreeterServer struct {
}

func (*UnimplementedGreeterServer) PostHello(ctx context.Context, req *PostHelloRequest) (*PostHelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostHello not implemented")
}
func (*UnimplementedGreeterServer) GetHello(ctx context.Context, req *GetHelloRequest) (*GetHelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHello not implemented")
}

func RegisterGreeterServer(s *grpc.Server, srv GreeterServer) {
	s.RegisterService(&_Greeter_serviceDesc, srv)
}

func _Greeter_PostHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostHelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).PostHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hello.Greeter/PostHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).PostHello(ctx, req.(*PostHelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_GetHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).GetHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hello.Greeter/GetHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).GetHello(ctx, req.(*GetHelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Greeter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "hello.Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PostHello",
			Handler:    _Greeter_PostHello_Handler,
		},
		{
			MethodName: "GetHello",
			Handler:    _Greeter_GetHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "servers/hello/hello.proto",
}
